import type { DASS21Question } from '../interface/forms';

export const dass21Questions: DASS21Question[] = [
  { id: 1, text: "Tôi thấy khó mà thoải mái được." },
  { id: 2, text: "Tôi cảm thấy khô miệng." },
  { id: 3, text: "Tôi dường như chẳng có chút cảm xúc tích cực nào." },
  { id: 4, text: "Tôi cảm thấy khó thở (thở gấp, khó thở dù chẳng làm việc gì nặng)." },
  { id: 5, text: "Tôi thấy khó bắt tay vào công việc." },
  { id: 6, text: "Tôi có xu hướng phản ứng thái quá với các tình huống." },
  { id: 7, text: "Tôi hay run (ví dụ: tay)." },
  { id: 8, text: "Tôi thấy mình đang suy nghĩ quá nhiều." },
  { id: 9, text: "Tôi lo lắng về những tình huống có thể làm tôi hoảng sợ hoặc biến tôi thành trò cười." },
  { id: 10, text: "Tôi thấy mình chẳng có gì để mong đợi cả." },
  { id: 11, text: "Tôi thấy bản thân dễ bị kích động." },
  { id: 12, text: "Tôi thấy khó thư giãn được." },
  { id: 13, text: "Tôi cảm thấy chán nản, buồn bã." },
  { id: 14, text: "Tôi không chấp nhận được việc có cái gì đó xen vào cản trở việc tôi đang làm." },
  { id: 15, text: "Tôi thấy mình gần như hoảng loạn." },
  { id: 16, text: "Tôi không thể hăng hái với bất kỳ việc gì nữa." },
  { id: 17, text: "Tôi cảm thấy mình chẳng đáng làm người." },
  { id: 18, text: "Tôi thấy mình khá dễ phật ý, tự ái." },
  { id: 19, text: "Tôi nghe thấy rõ tiếng nhịp tim dù không làm việc gì nặng cả (ví dụ: cảm thấy nhịp tim tăng, tim lỡ nhịp)." },
  { id: 20, text: "Tôi thấy sợ vô cớ." },
  { id: 21, text: "Tôi thấy cuộc sống vô nghĩa." },
];
